### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by bresu** [emergenz/pausebot#1]
Was Lele noch machen muss:

- [x] CSS für andere seiten

- [x] paste from clipboard button 

- [x] Schönere Schrift finden weil Lato suckt

- [x] Google AdSense endlich zum Laufenbringen

- [x] openCV ficken
