### ISSUE TITLE
SEO Todo

### ISSUE THREAD

**Issue by bresu** [emergenz/pausebot#4]
- [ ] www auf https umleiten

- [x] erste heading bearbeiten, damit  keywords beinhaltet und länger is **Your TikTok P**

- [x] ca 250 wörter text

- [x] h1 zu h2 ändern

- [x] MEHR TIK TOK KEYWORDS<
