### ISSUE TITLE
TODO Franz der pen-tester

### ISSUE THREAD

**Issue by bresu** [emergenz/pausebot#6]
**LEANDER ERKLÄREN WIE MAN SERVER STARTET**
- [x] pinger für website machen der den status code checkt

- [x] automatischer restart aufm server (alle 30min? wenn down?)

- [x] Terminal output saven für analyse (TIKTOK LINKS ABSPEICHERN)
