### ISSUE TITLE
Todo Franz

### ISSUE THREAD

**Issue by bresu** [emergenz/pausebot#8]
- [x] GIT PULL!
- [x] Display page fertig machen
- [x] adsense & analytics script in ALLE page header einbauen
- [x] media.net ding entfernen
- [x] mal wieder im issue "broken tiktoks" nachschauen warum die ned gehen
